# from django.conf import settings
# from django.core.mail import EmailMessage


# def send_proposal_for_review(proposal, recipient_email=None):
#     """
#     Emails the proposal's PDF to the sales manager (or a given recipient) for review.
#     Returns True on success, raises exception on failure.
#     """
#     if not proposal.generated_pdf:
#         raise ValueError("Proposal has no generated PDF. Export it first.")

#     recipient = recipient_email or settings.SALES_MANAGER_EMAIL
#     if not recipient:
#         raise ValueError("No recipient email configured (SALES_MANAGER_EMAIL is empty).")

#     subject = f"Proposal for Review: {proposal.title}"
#     body = f"""Hello,

# A new business proposal has been generated and is ready for your review.

# Proposal: {proposal.title}
# Estimated Cost: ${proposal.estimated_cost}
# Estimated Timeline: {proposal.estimated_timeline_weeks} weeks
# Status: {proposal.status}
# print(f"Sending email to {recipient}")

# Please find the full proposal attached as a PDF.

# This proposal was generated by the AI Business Proposal Assistant based on the client's RFP.

# Regards,
# AI Proposal System
# """

#     email = EmailMessage(
#         subject=subject,
#         body=body,
#         from_email=settings.EMAIL_HOST_USER,
#         to=[recipient],
#     )

#     with proposal.generated_pdf.open('rb') as f:
#         email.attach(
#             f"{proposal.title or 'proposal'}.pdf",
#             f.read(),
#             'application/pdf'
#         )

#     email.send(fail_silently=False)
#     return recipient


from django.conf import settings
from django.core.mail import EmailMultiAlternatives
from django.urls import reverse

from exporter.models import ProposalDelivery


def send_proposal_for_review(proposal, recipient_email=None):
    """
    Sends the generated proposal PDF to the client with
    Approve and Reject buttons.
    """

    if not proposal.generated_pdf:
        raise ValueError(
            "Proposal has no generated PDF. Export it first."
        )

    recipient = recipient_email

    if not recipient:
        raise ValueError(
            "No client email provided."
        )

    # Create delivery record
    delivery = ProposalDelivery.objects.create(
        proposal=proposal,
        sent_to_email=recipient
    )

    # URLs for Approve and Reject buttons
    approve_url = (
        f"{settings.SITE_URL}"
        f"{reverse('proposal-approve', args=[delivery.approval_token])}"
    )

    reject_url = (
        f"{settings.SITE_URL}"
        f"{reverse('proposal-reject', args=[delivery.approval_token])}"
    )

    subject = f"Proposal for Review: {proposal.title}"

    # Plain-text email
    body = f"""
Hello,

A new business proposal has been generated and is ready for your review.

Proposal: {proposal.title}
Estimated Cost: ${proposal.estimated_cost}
Estimated Timeline: {proposal.estimated_timeline_weeks} weeks

Please review the attached proposal.

Approve Proposal:
{approve_url}

Reject Proposal:
{reject_url}

This proposal was generated by the AI Business Proposal Assistant
based on the client's RFP.

Regards,
AI Proposal System
"""

    # HTML email
    html_body = f"""
<html>
<body>

<h2>Proposal for Review</h2>

<p>Hello,</p>

<p>
A new business proposal has been generated and is ready for your review.
</p>

<p>
<strong>Proposal:</strong> {proposal.title}
</p>

<p>
<strong>Estimated Cost:</strong> ${proposal.estimated_cost}
</p>

<p>
<strong>Estimated Timeline:</strong>
{proposal.estimated_timeline_weeks} weeks
</p>

<br>

<p>
Please review the attached proposal and select an option:
</p>

<br>

<a href="{approve_url}"
   style="
   background-color:#16a34a;
   color:white;
   padding:12px 22px;
   text-decoration:none;
   border-radius:6px;
   font-weight:bold;
   display:inline-block;
   ">
   ✓ Approve Proposal
</a>

&nbsp;&nbsp;

<a href="{reject_url}"
   style="
   background-color:#dc2626;
   color:white;
   padding:12px 22px;
   text-decoration:none;
   border-radius:6px;
   font-weight:bold;
   display:inline-block;
   ">
   ✕ Reject Proposal
</a>

<br><br>

<p>
The complete proposal is attached as a PDF.
</p>

<p>
Regards,<br>
AI Proposal System
</p>

</body>
</html>
"""

    email = EmailMultiAlternatives(
        subject=subject,
        body=body,
        from_email=settings.EMAIL_HOST_USER,
        to=[recipient],
    )

    # Add HTML version
    email.attach_alternative(
        html_body,
        "text/html"
    )

    # Attach proposal PDF
    with proposal.generated_pdf.open("rb") as f:
        email.attach(
            f"{proposal.title or 'proposal'}.pdf",
            f.read(),
            "application/pdf"
        )

    try:
        email.send(fail_silently=False)

        delivery.delivery_status = "sent"
        delivery.save(
            update_fields=["delivery_status"]
        )

    except Exception as e:

        delivery.delivery_status = "failed"
        delivery.delivery_error = str(e)

        delivery.save(
            update_fields=[
                "delivery_status",
                "delivery_error"
            ]
        )

        raise

    # Update proposal status
    proposal.status = "sent_for_review"
    proposal.save(
        update_fields=["status"]
    )

    return recipient