from django.conf import settings
from django.core.mail import EmailMessage


def send_proposal_for_review(proposal, recipient_email=None):
    """
    Emails the proposal's PDF to the sales manager (or a given recipient) for review.
    Returns True on success, raises exception on failure.
    """
    if not proposal.generated_pdf:
        raise ValueError("Proposal has no generated PDF. Export it first.")

    recipient = recipient_email or settings.SALES_MANAGER_EMAIL
    if not recipient:
        raise ValueError("No recipient email configured (SALES_MANAGER_EMAIL is empty).")

    subject = f"Proposal for Review: {proposal.title}"
    body = f"""Hello,

A new business proposal has been generated and is ready for your review.

Proposal: {proposal.title}
Estimated Cost: ${proposal.estimated_cost}
Estimated Timeline: {proposal.estimated_timeline_weeks} weeks
Status: {proposal.status}
print(f"Sending email to {recipient}")

Please find the full proposal attached as a PDF.

This proposal was generated by the AI Business Proposal Assistant based on the client's RFP.

Regards,
AI Proposal System
"""

    email = EmailMessage(
        subject=subject,
        body=body,
        from_email=settings.EMAIL_HOST_USER,
        to=[recipient],
    )

    with proposal.generated_pdf.open('rb') as f:
        email.attach(
            f"{proposal.title or 'proposal'}.pdf",
            f.read(),
            'application/pdf'
        )

    email.send(fail_silently=False)
    return recipient