# Generated by Django 6.0.7 on 2026-07-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('project_type', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('tech_stack', models.CharField(blank=True, max_length=500)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actual_duration_weeks', models.PositiveIntegerField(blank=True, null=True)),
                ('original_proposal_file', models.FileField(blank=True, null=True, upload_to='historical_proposals/')),
                ('is_indexed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
