# Generated by Django 6.0.7 on 2026-07-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RFP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='rfp_uploads/')),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('extracted_requirements', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('extracted', 'Text Extracted'), ('analyzed', 'AI Analyzed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
