# Generated by Django 6.0.7 on 2026-07-29 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge_base', '0001_initial'),
        ('rfp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('executive_summary', models.TextField(blank=True, null=True)),
                ('scope_of_work', models.TextField(blank=True, null=True)),
                ('technology_stack', models.TextField(blank=True, null=True)),
                ('deliverables', models.TextField(blank=True, null=True)),
                ('terms_and_conditions', models.TextField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cost_breakdown', models.JSONField(blank=True, null=True)),
                ('estimated_timeline_weeks', models.PositiveIntegerField(blank=True, null=True)),
                ('timeline_breakdown', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('sent_for_review', 'Sent for Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('generated_pdf', models.FileField(blank=True, null=True, upload_to='generated_pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referenced_projects', models.ManyToManyField(blank=True, related_name='used_in_proposals', to='knowledge_base.historicalproject')),
                ('rfp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='rfp.rfp')),
            ],
        ),
    ]
