# Generated by Django 5.2.6 on 2026-08-07 10:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exporter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaldelivery',
            name='approval_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
